{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Connect to your workspace"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ready to use Azure ML 1.46.0 to work with ELP_test\n"
     ]
    }
   ],
   "source": [
    "import azureml.core\n",
    "from azureml.core import Workspace\n",
    "\n",
    "# Load the workspace from the saved config file\n",
    "ws = Workspace.from_config()\n",
    "print(\"Ready to use Azure ML {} to work with {}\".format(azureml.core.VERSION, ws.name))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Train and register a model\n",
    "\n",
    "Now let's train and register a model to deploy in a batch inferencing pipeline."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [60], line 4\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mazureml\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcore\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Experiment, Model\n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m# Create an Azure ML experiment in your workspace\u001b[39;00m\n\u001b[0;32m----> 4\u001b[0m experiment \u001b[38;5;241m=\u001b[39m \u001b[43mExperiment\u001b[49m\u001b[43m(\u001b[49m\u001b[43mworkspace\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mws\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmslearn-train-diabetes\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      5\u001b[0m run \u001b[38;5;241m=\u001b[39m experiment\u001b[38;5;241m.\u001b[39mstart_logging(snapshot_directory\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mStarting experiment:\u001b[39m\u001b[38;5;124m\"\u001b[39m, experiment\u001b[38;5;241m.\u001b[39mname)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/core/experiment.py:133\u001b[0m, in \u001b[0;36mExperiment.__init__\u001b[0;34m(self, workspace, name, _skip_name_validation, _id, _archived_time, _create_in_cloud, _experiment_dto, **kwargs)\u001b[0m\n\u001b[1;32m    131\u001b[0m \u001b[39m# Get or create the experiment from the workspace\u001b[39;00m\n\u001b[1;32m    132\u001b[0m \u001b[39mif\u001b[39;00m _create_in_cloud:\n\u001b[0;32m--> 133\u001b[0m     experiment \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_workspace_client\u001b[39m.\u001b[39;49mget_or_create_experiment(experiment_name\u001b[39m=\u001b[39;49mname)\n\u001b[1;32m    134\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_id \u001b[39m=\u001b[39m experiment\u001b[39m.\u001b[39mexperiment_id\n\u001b[1;32m    135\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_archived_time \u001b[39m=\u001b[39m experiment\u001b[39m.\u001b[39marchived_time\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/workspace_client.py:91\u001b[0m, in \u001b[0;36mWorkspaceClient.get_or_create_experiment\u001b[0;34m(self, experiment_name, is_async)\u001b[0m\n\u001b[1;32m     89\u001b[0m \u001b[39m# Client Get, Create on NotFound\u001b[39;00m\n\u001b[1;32m     90\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 91\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_experiment(experiment_name, is_async)\n\u001b[1;32m     92\u001b[0m \u001b[39mexcept\u001b[39;00m ServiceException \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m     93\u001b[0m     \u001b[39mif\u001b[39;00m e\u001b[39m.\u001b[39mstatus_code \u001b[39m==\u001b[39m \u001b[39m404\u001b[39m:\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/workspace_client.py:280\u001b[0m, in \u001b[0;36mWorkspaceClient.get_experiment\u001b[0;34m(self, experiment_name, is_async)\u001b[0m\n\u001b[1;32m    265\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_experiment\u001b[39m(\u001b[39mself\u001b[39m, experiment_name, is_async\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m):\n\u001b[1;32m    266\u001b[0m     \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    267\u001b[0m \u001b[39m    get experiment by name\u001b[39;00m\n\u001b[1;32m    268\u001b[0m \u001b[39m    :param experiment_name: experiment name (required)\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    277\u001b[0m \u001b[39m        return: ~_restclient.models.ExperimentDto\u001b[39;00m\n\u001b[1;32m    278\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 280\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_with_workspace_arguments(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_client\u001b[39m.\u001b[39;49mexperiment\u001b[39m.\u001b[39;49mget,\n\u001b[1;32m    281\u001b[0m                                                   experiment_name\u001b[39m=\u001b[39;49mexperiment_name,\n\u001b[1;32m    282\u001b[0m                                                   is_async\u001b[39m=\u001b[39;49mis_async)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/workspace_client.py:72\u001b[0m, in \u001b[0;36mWorkspaceClient._execute_with_workspace_arguments\u001b[0;34m(self, func, *args, **kwargs)\u001b[0m\n\u001b[1;32m     71\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_with_workspace_arguments\u001b[39m(\u001b[39mself\u001b[39m, func, \u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[0;32m---> 72\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_with_arguments(func, copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_workspace_arguments), \u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py:589\u001b[0m, in \u001b[0;36mClientBase._execute_with_arguments\u001b[0;34m(self, func, args_list, *args, **kwargs)\u001b[0m\n\u001b[1;32m    587\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_call_paginated_api(func, \u001b[39m*\u001b[39margs_list, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m    588\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 589\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_call_api(func, \u001b[39m*\u001b[39;49margs_list, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    590\u001b[0m \u001b[39mexcept\u001b[39;00m ErrorResponseException \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    591\u001b[0m     \u001b[39mraise\u001b[39;00m ServiceException(e)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py:245\u001b[0m, in \u001b[0;36mClientBase._call_api\u001b[0;34m(self, func, *args, **kwargs)\u001b[0m\n\u001b[1;32m    243\u001b[0m     \u001b[39mreturn\u001b[39;00m AsyncTask(future, _ident\u001b[39m=\u001b[39mident, _parent_logger\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_logger)\n\u001b[1;32m    244\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 245\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_with_base_arguments(func, \u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py:333\u001b[0m, in \u001b[0;36mClientBase._execute_with_base_arguments\u001b[0;34m(self, func, *args, **kwargs)\u001b[0m\n\u001b[1;32m    331\u001b[0m back_off \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mbackoff_factor\n\u001b[1;32m    332\u001b[0m total_retry \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mretries \u001b[39m<\u001b[39m \u001b[39m0\u001b[39m \u001b[39melse\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mretries\n\u001b[0;32m--> 333\u001b[0m \u001b[39mreturn\u001b[39;00m ClientBase\u001b[39m.\u001b[39;49m_execute_func_internal(\n\u001b[1;32m    334\u001b[0m     back_off, total_retry, \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_logger, func, _noop_reset, \u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/clientbase.py:358\u001b[0m, in \u001b[0;36mClientBase._execute_func_internal\u001b[0;34m(cls, back_off, total_retry, logger, func, reset_func, *args, **kwargs)\u001b[0m\n\u001b[1;32m    356\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    357\u001b[0m     logger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mClientBase: Calling \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m with url \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(func_name, func_url))\n\u001b[0;32m--> 358\u001b[0m     response \u001b[39m=\u001b[39m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    359\u001b[0m     \u001b[39mif\u001b[39;00m (\u001b[39misinstance\u001b[39m(response, Response) \u001b[39mand\u001b[39;00m \u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m_is_retryable_status_code(response\u001b[39m.\u001b[39mstatus_code)\n\u001b[1;32m    360\u001b[0m             \u001b[39mand\u001b[39;00m left_retry \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m):\n\u001b[1;32m    361\u001b[0m         \u001b[39m# This is the handle the error case 1. response.raise_for_status only throws HTTPError exception.\u001b[39;00m\n\u001b[1;32m    362\u001b[0m         \u001b[39m# if the status_code is retryable and it is not the last retry, then the exception is thrown.\u001b[39;00m\n\u001b[1;32m    363\u001b[0m         \u001b[39m# Otherwise, we will return the response directly.\u001b[39;00m\n\u001b[1;32m    364\u001b[0m         response\u001b[39m.\u001b[39mraise_for_status()\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/_restclient/operations/experiment_operations.py:86\u001b[0m, in \u001b[0;36mExperimentOperations.get\u001b[0;34m(self, subscription_id, resource_group_name, workspace_name, experiment_name, view_type, custom_headers, raw, **operation_config)\u001b[0m\n\u001b[1;32m     84\u001b[0m \u001b[39m# Construct and send request\u001b[39;00m\n\u001b[1;32m     85\u001b[0m request \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_client\u001b[39m.\u001b[39mget(url, query_parameters)\n\u001b[0;32m---> 86\u001b[0m response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_client\u001b[39m.\u001b[39;49msend(request, header_parameters, stream\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49moperation_config)\n\u001b[1;32m     88\u001b[0m \u001b[39mif\u001b[39;00m response\u001b[39m.\u001b[39mstatus_code \u001b[39mnot\u001b[39;00m \u001b[39min\u001b[39;00m [\u001b[39m200\u001b[39m]:\n\u001b[1;32m     89\u001b[0m     \u001b[39mraise\u001b[39;00m models\u001b[39m.\u001b[39mErrorResponseException(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_deserialize, response)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/msrest/service_client.py:336\u001b[0m, in \u001b[0;36mServiceClient.send\u001b[0;34m(self, request, headers, content, **kwargs)\u001b[0m\n\u001b[1;32m    334\u001b[0m kwargs\u001b[39m.\u001b[39msetdefault(\u001b[39m'\u001b[39m\u001b[39mstream\u001b[39m\u001b[39m'\u001b[39m, \u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m    335\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 336\u001b[0m     pipeline_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig\u001b[39m.\u001b[39;49mpipeline\u001b[39m.\u001b[39;49mrun(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    337\u001b[0m     \u001b[39m# There is too much thing that expects this method to return a \"requests.Response\"\u001b[39;00m\n\u001b[1;32m    338\u001b[0m     \u001b[39m# to break it in a compatible release.\u001b[39;00m\n\u001b[1;32m    339\u001b[0m     \u001b[39m# Also, to be pragmatic in the \"sync\" world \"requests\" rules anyway.\u001b[39;00m\n\u001b[1;32m    340\u001b[0m     \u001b[39m# However, attach the Universal HTTP response\u001b[39;00m\n\u001b[1;32m    341\u001b[0m     \u001b[39m# to get the streaming generator.\u001b[39;00m\n\u001b[1;32m    342\u001b[0m     response \u001b[39m=\u001b[39m pipeline_response\u001b[39m.\u001b[39mhttp_response\u001b[39m.\u001b[39minternal_response\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py:197\u001b[0m, in \u001b[0;36mPipeline.run\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    195\u001b[0m pipeline_request \u001b[39m=\u001b[39m Request(request, context)  \u001b[39m# type: Request[HTTPRequestType]\u001b[39;00m\n\u001b[1;32m    196\u001b[0m first_node \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_impl_policies[\u001b[39m0\u001b[39m] \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_impl_policies \u001b[39melse\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sender\n\u001b[0;32m--> 197\u001b[0m \u001b[39mreturn\u001b[39;00m first_node\u001b[39m.\u001b[39;49msend(pipeline_request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/msrest/pipeline/__init__.py:150\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    148\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_policy\u001b[39m.\u001b[39mon_request(request, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m    149\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 150\u001b[0m     response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mnext\u001b[39m.\u001b[39;49msend(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    151\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m:\n\u001b[1;32m    152\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_policy\u001b[39m.\u001b[39mon_exception(request, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/msrest/pipeline/requests.py:65\u001b[0m, in \u001b[0;36mRequestsCredentialsPolicy.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m     63\u001b[0m session \u001b[39m=\u001b[39m request\u001b[39m.\u001b[39mcontext\u001b[39m.\u001b[39msession\n\u001b[1;32m     64\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 65\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_creds\u001b[39m.\u001b[39;49msigned_session(session)\n\u001b[1;32m     66\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m: \u001b[39m# Credentials does not support session injection\u001b[39;00m\n\u001b[1;32m     67\u001b[0m     _LOGGER\u001b[39m.\u001b[39mwarning(\u001b[39m\"\u001b[39m\u001b[39mYour credentials class does not support session injection. Performance will not be at the maximum.\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/core/authentication.py:251\u001b[0m, in \u001b[0;36mAbstractAuthentication.signed_session\u001b[0;34m(self, session)\u001b[0m\n\u001b[1;32m    240\u001b[0m \u001b[39m\"\"\"Add the authorization header as a persisted header on an HTTP session.\u001b[39;00m\n\u001b[1;32m    241\u001b[0m \n\u001b[1;32m    242\u001b[0m \u001b[39mAny new requests sent by the session will contain the authorization header.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    248\u001b[0m \u001b[39m:rtype: requests.sessions.Session\u001b[39;00m\n\u001b[1;32m    249\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    250\u001b[0m session \u001b[39m=\u001b[39m session \u001b[39mor\u001b[39;00m Session()\n\u001b[0;32m--> 251\u001b[0m session\u001b[39m.\u001b[39mheaders\u001b[39m.\u001b[39mupdate(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_authentication_header())\n\u001b[1;32m    252\u001b[0m \u001b[39mreturn\u001b[39;00m session\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/core/authentication.py:128\u001b[0m, in \u001b[0;36mAbstractAuthentication.get_authentication_header\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    118\u001b[0m \u001b[39m\"\"\"Return the HTTP authorization header.\u001b[39;00m\n\u001b[1;32m    119\u001b[0m \n\u001b[1;32m    120\u001b[0m \u001b[39mThe authorization header contains the user access token for access authorization against the service.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    124\u001b[0m \u001b[39m:rtype: dict\u001b[39;00m\n\u001b[1;32m    125\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m    126\u001b[0m \u001b[39m# We return a new dictionary each time, as some functions modify the headers returned\u001b[39;00m\n\u001b[1;32m    127\u001b[0m \u001b[39m# by this function.\u001b[39;00m\n\u001b[0;32m--> 128\u001b[0m auth_header \u001b[39m=\u001b[39m {\u001b[39m\"\u001b[39m\u001b[39mAuthorization\u001b[39m\u001b[39m\"\u001b[39m: \u001b[39m\"\u001b[39m\u001b[39mBearer \u001b[39m\u001b[39m\"\u001b[39m \u001b[39m+\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_get_arm_token()}\n\u001b[1;32m    129\u001b[0m \u001b[39mreturn\u001b[39;00m auth_header\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/core/authentication.py:386\u001b[0m, in \u001b[0;36m_login_on_failure_decorator.<locals>.actual_decorator.<locals>.wrapper\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    384\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    385\u001b[0m     start_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[0;32m--> 386\u001b[0m     lock_to_use\u001b[39m.\u001b[39;49macquire()\n\u001b[1;32m    387\u001b[0m     duration \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime() \u001b[39m-\u001b[39m start_time\n\u001b[1;32m    388\u001b[0m     \u001b[39mif\u001b[39;00m duration \u001b[39m>\u001b[39m ACQUIRE_DURATION_THRESHOLD:\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "from azureml.core import Experiment, Model\n",
    "\n",
    "# Create an Azure ML experiment in your workspace\n",
    "experiment = Experiment(workspace=ws, name='mslearn-train-diabetes')\n",
    "run = experiment.start_logging(snapshot_directory=None)\n",
    "print(\"Starting experiment:\", experiment.name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pipeline\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "# Create a folder for the pipeline step files\n",
    "experiment_folder = 'pipeline'\n",
    "os.makedirs(experiment_folder, exist_ok=True)\n",
    "\n",
    "print(experiment_folder)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing cluster, use it.\n"
     ]
    }
   ],
   "source": [
    "from azureml.core.compute import ComputeTarget, AmlCompute\n",
    "from azureml.core.compute_target import ComputeTargetException\n",
    "\n",
    "cluster_name = \"your-compute-cluster\"\n",
    "\n",
    "try:\n",
    "    # Check for existing compute target\n",
    "    pipeline_cluster = ComputeTarget(workspace=ws, name=cluster_name)\n",
    "    print('Found existing cluster, use it.')\n",
    "except ComputeTargetException:\n",
    "    # If it doesn't already exist, create it\n",
    "    try:\n",
    "        compute_config = AmlCompute.provisioning_configuration(vm_size='STANDARD_DS11_V2', max_nodes=2)\n",
    "        pipeline_cluster = ComputeTarget.create(ws, cluster_name, compute_config)\n",
    "        pipeline_cluster.wait_for_completion(show_output=True)\n",
    "    except Exception as ex:\n",
    "        print(ex)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Run configuration created.\n"
     ]
    }
   ],
   "source": [
    "from azureml.core import Environment\n",
    "from azureml.core.runconfig import RunConfiguration\n",
    "from azureml.core import Workspace, Dataset\n",
    "\n",
    "\n",
    "# Create a Python environment for the experiment (from a .yml file)\n",
    "experiment_env = Environment.from_conda_specification(\"experiment_env\", experiment_folder + \"/experiment_env.yml\")\n",
    "\n",
    "# Register the environment \n",
    "experiment_env.register(workspace=ws)\n",
    "registered_env = Environment.get(ws, 'experiment_env')\n",
    "\n",
    "# Create a new runconfig object for the pipeline\n",
    "pipeline_run_config = RunConfiguration()\n",
    "\n",
    "# Use the compute you created above. \n",
    "pipeline_run_config.target = pipeline_cluster\n",
    "\n",
    "# Assign the environment to the run configuration\n",
    "pipeline_run_config.environment = registered_env\n",
    "\n",
    "print (\"Run configuration created.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pipeline steps defined\n"
     ]
    }
   ],
   "source": [
    "from azureml.data import OutputFileDatasetConfig\n",
    "from azureml.pipeline.steps import PythonScriptStep\n",
    "from azureml.core import Workspace, Dataset\n",
    "\n",
    "\n",
    "# Get the training dataset\n",
    "dataset = Dataset.get_by_name(ws, name='batch-data') # how get data there remember\n",
    "dataset.download(target_path='.', overwrite=True)\n",
    "\n",
    "# Create an OutputFileDatasetConfig (temporary Data Reference) for data passed from step 1 to step 2\n",
    "prepped_data = OutputFileDatasetConfig(\"prepped_data\")\n",
    "\n",
    "# Step 1, Run the data prep script\n",
    "prep_step = PythonScriptStep(name = \"Prepare Data\",\n",
    "                                source_directory = experiment_folder,\n",
    "                                script_name = \"prep.py\",\n",
    "                                arguments = ['--input-data', dataset.as_named_input('raw_data'),\n",
    "                                             '--prepped-data', prepped_data],\n",
    "                                compute_target = pipeline_cluster,\n",
    "                                runconfig = pipeline_run_config,\n",
    "                                allow_reuse = True)\n",
    "\n",
    "# Step 2, run the training script\n",
    "train_step = PythonScriptStep(name = \"Train and Register Model\",\n",
    "                                source_directory = experiment_folder,\n",
    "                                script_name = \"train.py\",\n",
    "                                arguments = ['--training-data', prepped_data.as_input()],\n",
    "                                compute_target = pipeline_cluster,\n",
    "                                runconfig = pipeline_run_config,\n",
    "                                allow_reuse = True)\n",
    "\n",
    "print(\"Pipeline steps defined\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pipeline is built.\n",
      "Created step Prepare Data [a3728aa1][39031545-aca3-4467-9fa0-9841471149f2], (This step will run and generate new outputs)\n",
      "Created step Train and Register Model [257d50b4][a90f9c35-919b-4b94-af2c-8145b5503094], (This step will run and generate new outputs)\n",
      "Submitted PipelineRun 2e4d6b75-10cc-47f8-8a20-bffe388663d3\n",
      "Link to Azure Machine Learning Portal: https://ml.azure.com/runs/2e4d6b75-10cc-47f8-8a20-bffe388663d3?wsid=/subscriptions/0aa54ba3-0284-4c54-8170-18cdcbefdf5f/resourcegroups/ELP/workspaces/ELP_test&tid=875c414e-5d00-4cdb-b77a-deae5d6ab201\n",
      "Pipeline submitted for execution.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "31efd51e06344d45acadd33eb69b17df",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "_PipelineWidget(widget_settings={'childWidgetDisplay': 'popup', 'send_telemetry': False, 'log_level': 'INFO', …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/aml.mini.widget.v1": "{\"status\": \"Failed\", \"workbench_run_details_uri\": \"https://ml.azure.com/runs/2e4d6b75-10cc-47f8-8a20-bffe388663d3?wsid=/subscriptions/0aa54ba3-0284-4c54-8170-18cdcbefdf5f/resourcegroups/ELP/workspaces/ELP_test&tid=875c414e-5d00-4cdb-b77a-deae5d6ab201\", \"run_id\": \"2e4d6b75-10cc-47f8-8a20-bffe388663d3\", \"run_properties\": {\"run_id\": \"2e4d6b75-10cc-47f8-8a20-bffe388663d3\", \"created_utc\": \"2022-10-11T16:29:26.743177Z\", \"properties\": {\"azureml.runsource\": \"azureml.PipelineRun\", \"runSource\": \"SDK\", \"runType\": \"SDK\", \"azureml.parameters\": \"{}\", \"azureml.continue_on_step_failure\": \"False\", \"azureml.continue_on_failed_optional_input\": \"True\", \"azureml.pipelineComponent\": \"pipelinerun\"}, \"tags\": {}, \"end_time_utc\": \"2022-10-11T16:44:26.601586Z\", \"status\": \"Failed\", \"log_files\": {\"logs/azureml/executionlogs.txt\": \"https://elptest8765985607.blob.core.windows.net/azureml/ExperimentRun/dcid.2e4d6b75-10cc-47f8-8a20-bffe388663d3/logs/azureml/executionlogs.txt?sv=2019-07-07&sr=b&sig=nGbWCYHGCU%2BtTiQda3mMg6Vu2qIFeo3PL2rBSiKjdl8%3D&skoid=ae401e29-96dd-4cdc-9b05-d5473e205090&sktid=875c414e-5d00-4cdb-b77a-deae5d6ab201&skt=2022-10-11T13%3A59%3A07Z&ske=2022-10-12T22%3A09%3A07Z&sks=b&skv=2019-07-07&st=2022-10-11T16%3A30%3A02Z&se=2022-10-12T00%3A40%3A02Z&sp=r\", \"logs/azureml/stderrlogs.txt\": \"https://elptest8765985607.blob.core.windows.net/azureml/ExperimentRun/dcid.2e4d6b75-10cc-47f8-8a20-bffe388663d3/logs/azureml/stderrlogs.txt?sv=2019-07-07&sr=b&sig=CM7T6tPnTpu04APeQ5BEUUbFvu5Naktaj9GfdBqTwU0%3D&skoid=ae401e29-96dd-4cdc-9b05-d5473e205090&sktid=875c414e-5d00-4cdb-b77a-deae5d6ab201&skt=2022-10-11T13%3A59%3A07Z&ske=2022-10-12T22%3A09%3A07Z&sks=b&skv=2019-07-07&st=2022-10-11T16%3A30%3A02Z&se=2022-10-12T00%3A40%3A02Z&sp=r\", \"logs/azureml/stdoutlogs.txt\": \"https://elptest8765985607.blob.core.windows.net/azureml/ExperimentRun/dcid.2e4d6b75-10cc-47f8-8a20-bffe388663d3/logs/azureml/stdoutlogs.txt?sv=2019-07-07&sr=b&sig=kjrwhfGfJ8oKZoJmxZ3Bwt%2FmONJ3CDDtBtD%2BsvnVXRY%3D&skoid=ae401e29-96dd-4cdc-9b05-d5473e205090&sktid=875c414e-5d00-4cdb-b77a-deae5d6ab201&skt=2022-10-11T13%3A59%3A07Z&ske=2022-10-12T22%3A09%3A07Z&sks=b&skv=2019-07-07&st=2022-10-11T16%3A30%3A02Z&se=2022-10-12T00%3A40%3A02Z&sp=r\"}, \"log_groups\": [[\"logs/azureml/executionlogs.txt\", \"logs/azureml/stderrlogs.txt\", \"logs/azureml/stdoutlogs.txt\"]], \"run_duration\": \"0:14:59\", \"run_number\": \"1665505766\", \"run_queued_details\": {\"status\": \"Failed\", \"details\": null}}, \"child_runs\": [{\"run_id\": \"\", \"name\": \"Prepare Data\", \"status\": \"NotStarted\", \"start_time\": \"\", \"created_time\": \"\", \"end_time\": \"\", \"duration\": \"\"}, {\"run_id\": \"\", \"name\": \"Train and Register Model\", \"status\": \"NotStarted\", \"start_time\": \"\", \"created_time\": \"\", \"end_time\": \"\", \"duration\": \"\"}], \"children_metrics\": {\"categories\": null, \"series\": null, \"metricName\": null}, \"run_metrics\": [], \"run_logs\": \"[2022-10-11 16:29:29Z] Submitting 1 runs, first five are: a3728aa1:daef3cbb-cb28-4b26-ac23-e205b5fb2562\\n[2022-10-11 16:44:25Z] Execution of experiment failed, update experiment status and cancel running nodes.\\n\\nError occurred: Pipeline has some failed steps. See child run or execution logs for more details.\\n\", \"graph\": {\"datasource_nodes\": {\"a8062fa1\": {\"node_id\": \"a8062fa1\", \"name\": \"batch-data\"}}, \"module_nodes\": {\"a3728aa1\": {\"node_id\": \"a3728aa1\", \"name\": \"Prepare Data\", \"status\": \"NotStarted\"}, \"257d50b4\": {\"node_id\": \"257d50b4\", \"name\": \"Train and Register Model\", \"status\": \"NotStarted\"}}, \"edges\": [{\"source_node_id\": \"a8062fa1\", \"source_node_name\": \"batch-data\", \"source_name\": \"data\", \"target_name\": \"raw_data\", \"dst_node_id\": \"a3728aa1\", \"dst_node_name\": \"Prepare Data\"}, {\"source_node_id\": \"a3728aa1\", \"source_node_name\": \"Prepare Data\", \"source_name\": \"prepped_data\", \"target_name\": \"input_12f5212d\", \"dst_node_id\": \"257d50b4\", \"dst_node_name\": \"Train and Register Model\"}], \"child_runs\": [{\"run_id\": \"\", \"name\": \"Prepare Data\", \"status\": \"NotStarted\", \"start_time\": \"\", \"created_time\": \"\", \"end_time\": \"\", \"duration\": \"\"}, {\"run_id\": \"\", \"name\": \"Train and Register Model\", \"status\": \"NotStarted\", \"start_time\": \"\", \"created_time\": \"\", \"end_time\": \"\", \"duration\": \"\"}]}, \"widget_settings\": {\"childWidgetDisplay\": \"popup\", \"send_telemetry\": false, \"log_level\": \"INFO\", \"sdk_version\": \"1.46.0\"}, \"loading\": false}"
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PipelineRunId: 2e4d6b75-10cc-47f8-8a20-bffe388663d3\n",
      "Link to Azure Machine Learning Portal: https://ml.azure.com/runs/2e4d6b75-10cc-47f8-8a20-bffe388663d3?wsid=/subscriptions/0aa54ba3-0284-4c54-8170-18cdcbefdf5f/resourcegroups/ELP/workspaces/ELP_test&tid=875c414e-5d00-4cdb-b77a-deae5d6ab201\n",
      "PipelineRun Status: Running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Expected a StepRun object but received <class 'azureml.core.run.Run'> instead.\n",
      "This usually indicates a package conflict with one of the dependencies of azureml-core or azureml-pipeline-core.\n",
      "Please check for package conflicts in your python environment\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n"
     ]
    },
    {
     "ename": "ActivityFailedException",
     "evalue": "ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"{\\\"NonCompliant\\\":\\\"Process '/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/bin/python' exited with code 1 and error message 'Execution failed. Process exited with status code 1. Error: Traceback (most recent call last):\\\\n  File \\\\\\\"prep.py\\\\\\\", line 19, in <module>\\\\n    df = pd.read_csv(\\\\\\\"/home/saim/Desktop/abor\\\\\\\", sep='\\\\\\\\t')\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\", line 211, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\", line 317, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 950, in read_csv\\\\n    return _read(filepath_or_buffer, kwds)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 605, in _read\\\\n    parser = TextFileReader(filepath_or_buffer, **kwds)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 1442, in __init__\\\\n    self._engine = self._make_engine(f, self.engine)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 1729, in _make_engine\\\\n    self.handles = get_handle(\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/common.py\\\\\\\", line 857, in get_handle\\\\n    handle = open(\\\\nFileNotFoundError: [Errno 2] No such file or directory: '/home/saim/Desktop/abor'\\\\n\\\\n'. Please check the log file 'user_logs/std_log.txt' for more details.\\\"}\\n{\\n  \\\"code\\\": \\\"ExecutionFailed\\\",\\n  \\\"target\\\": \\\"\\\",\\n  \\\"category\\\": \\\"UserError\\\",\\n  \\\"error_details\\\": [\\n    {\\n      \\\"key\\\": \\\"exit_codes\\\",\\n      \\\"value\\\": \\\"1\\\"\\n    }\\n  ]\\n}\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"{\\\\\\\"NonCompliant\\\\\\\":\\\\\\\"Process '/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/bin/python' exited with code 1 and error message 'Execution failed. Process exited with status code 1. Error: Traceback (most recent call last):\\\\\\\\n  File \\\\\\\\\\\\\\\"prep.py\\\\\\\\\\\\\\\", line 19, in <module>\\\\\\\\n    df = pd.read_csv(\\\\\\\\\\\\\\\"/home/saim/Desktop/abor\\\\\\\\\\\\\\\", sep='\\\\\\\\\\\\\\\\t')\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\\\\\\\\\", line 211, in wrapper\\\\\\\\n    return func(*args, **kwargs)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\\\\\\\\\", line 317, in wrapper\\\\\\\\n    return func(*args, **kwargs)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 950, in read_csv\\\\\\\\n    return _read(filepath_or_buffer, kwds)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 605, in _read\\\\\\\\n    parser = TextFileReader(filepath_or_buffer, **kwds)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 1442, in __init__\\\\\\\\n    self._engine = self._make_engine(f, self.engine)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 1729, in _make_engine\\\\\\\\n    self.handles = get_handle(\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/common.py\\\\\\\\\\\\\\\", line 857, in get_handle\\\\\\\\n    handle = open(\\\\\\\\nFileNotFoundError: [Errno 2] No such file or directory: '/home/saim/Desktop/abor'\\\\\\\\n\\\\\\\\n'. Please check the log file 'user_logs/std_log.txt' for more details.\\\\\\\"}\\\\n{\\\\n  \\\\\\\"code\\\\\\\": \\\\\\\"ExecutionFailed\\\\\\\",\\\\n  \\\\\\\"target\\\\\\\": \\\\\\\"\\\\\\\",\\\\n  \\\\\\\"category\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n  \\\\\\\"error_details\\\\\\\": [\\\\n    {\\\\n      \\\\\\\"key\\\\\\\": \\\\\\\"exit_codes\\\\\\\",\\\\n      \\\\\\\"value\\\\\\\": \\\\\\\"1\\\\\\\"\\\\n    }\\\\n  ]\\\\n}\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/pipeline/core/run.py:295\u001b[0m, in \u001b[0;36mPipelineRun.wait_for_completion\u001b[0;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[1;32m    294\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 295\u001b[0m     step_run\u001b[39m.\u001b[39;49mwait_for_completion(timeout_seconds\u001b[39m=\u001b[39;49mtimeout_seconds \u001b[39m-\u001b[39;49m time_elapsed,\n\u001b[1;32m    296\u001b[0m                                  raise_on_error\u001b[39m=\u001b[39;49mraise_on_error)\n\u001b[1;32m    297\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    298\u001b[0m     \u001b[39m# If there are package conflicts in the user's environment, the run rehydration\u001b[39;00m\n\u001b[1;32m    299\u001b[0m     \u001b[39m# will not work and we will receive a Run object instead of StepRun.\u001b[39;00m\n\u001b[1;32m    300\u001b[0m     \u001b[39m# Run.wait_for_completion() does not have a parameter timeout_seconds, which\u001b[39;00m\n\u001b[1;32m    301\u001b[0m     \u001b[39m# will generate a TypeError here.  As a workaround, call the method without\u001b[39;00m\n\u001b[1;32m    302\u001b[0m     \u001b[39m# this parameter.\u001b[39;00m\n",
      "\u001b[0;31mTypeError\u001b[0m: wait_for_completion() got an unexpected keyword argument 'timeout_seconds'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mActivityFailedException\u001b[0m                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [69], line 15\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPipeline submitted for execution.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m     14\u001b[0m RunDetails(pipeline_run)\u001b[38;5;241m.\u001b[39mshow()\n\u001b[0;32m---> 15\u001b[0m \u001b[43mpipeline_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mshow_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/pipeline/core/run.py:310\u001b[0m, in \u001b[0;36mPipelineRun.wait_for_completion\u001b[0;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[1;32m    303\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39misinstance\u001b[39m(step_run, StepRun):\n\u001b[1;32m    304\u001b[0m     module_logger\u001b[39m.\u001b[39mwarning(\n\u001b[1;32m    305\u001b[0m         \u001b[39m'\u001b[39m\u001b[39mExpected a StepRun object but received \u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m    306\u001b[0m         \u001b[39m+\u001b[39m \u001b[39mstr\u001b[39m(\u001b[39mtype\u001b[39m(step_run)) \u001b[39m+\u001b[39m \u001b[39m'\u001b[39m\u001b[39m instead.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m'\u001b[39m\n\u001b[1;32m    307\u001b[0m         \u001b[39m+\u001b[39m \u001b[39m'\u001b[39m\u001b[39mThis usually indicates a package conflict with one of the dependencies of \u001b[39m\u001b[39m'\u001b[39m\n\u001b[1;32m    308\u001b[0m         \u001b[39m+\u001b[39m \u001b[39m'\u001b[39m\u001b[39mazureml-core or azureml-pipeline-core.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m'\u001b[39m\n\u001b[1;32m    309\u001b[0m         \u001b[39m+\u001b[39m \u001b[39m'\u001b[39m\u001b[39mPlease check for package conflicts in your python environment\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m--> 310\u001b[0m     step_run\u001b[39m.\u001b[39;49mwait_for_completion(raise_on_error\u001b[39m=\u001b[39;49mraise_on_error)\n\u001b[1;32m    311\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    312\u001b[0m     \u001b[39m# Different error than the run rehydration issue\u001b[39;00m\n\u001b[1;32m    313\u001b[0m     \u001b[39mraise\u001b[39;00m e\n",
      "File \u001b[0;32m~/azure/azure_venv/lib/python3.8/site-packages/azureml/core/run.py:876\u001b[0m, in \u001b[0;36mRun.wait_for_completion\u001b[0;34m(self, show_output, wait_post_processing, raise_on_error)\u001b[0m\n\u001b[1;32m    873\u001b[0m         error \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mDetailed error not set on the Run. Please check the logs for details.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    875\u001b[0m     \u001b[39mif\u001b[39;00m raise_on_error:\n\u001b[0;32m--> 876\u001b[0m         \u001b[39mraise\u001b[39;00m ActivityFailedException(error_details\u001b[39m=\u001b[39mjson\u001b[39m.\u001b[39mdumps(error, indent\u001b[39m=\u001b[39m\u001b[39m4\u001b[39m))\n\u001b[1;32m    878\u001b[0m \u001b[39mreturn\u001b[39;00m final_details\n",
      "\u001b[0;31mActivityFailedException\u001b[0m: ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"{\\\"NonCompliant\\\":\\\"Process '/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/bin/python' exited with code 1 and error message 'Execution failed. Process exited with status code 1. Error: Traceback (most recent call last):\\\\n  File \\\\\\\"prep.py\\\\\\\", line 19, in <module>\\\\n    df = pd.read_csv(\\\\\\\"/home/saim/Desktop/abor\\\\\\\", sep='\\\\\\\\t')\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\", line 211, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\", line 317, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 950, in read_csv\\\\n    return _read(filepath_or_buffer, kwds)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 605, in _read\\\\n    parser = TextFileReader(filepath_or_buffer, **kwds)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 1442, in __init__\\\\n    self._engine = self._make_engine(f, self.engine)\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\", line 1729, in _make_engine\\\\n    self.handles = get_handle(\\\\n  File \\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/common.py\\\\\\\", line 857, in get_handle\\\\n    handle = open(\\\\nFileNotFoundError: [Errno 2] No such file or directory: '/home/saim/Desktop/abor'\\\\n\\\\n'. Please check the log file 'user_logs/std_log.txt' for more details.\\\"}\\n{\\n  \\\"code\\\": \\\"ExecutionFailed\\\",\\n  \\\"target\\\": \\\"\\\",\\n  \\\"category\\\": \\\"UserError\\\",\\n  \\\"error_details\\\": [\\n    {\\n      \\\"key\\\": \\\"exit_codes\\\",\\n      \\\"value\\\": \\\"1\\\"\\n    }\\n  ]\\n}\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"{\\\\\\\"NonCompliant\\\\\\\":\\\\\\\"Process '/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/bin/python' exited with code 1 and error message 'Execution failed. Process exited with status code 1. Error: Traceback (most recent call last):\\\\\\\\n  File \\\\\\\\\\\\\\\"prep.py\\\\\\\\\\\\\\\", line 19, in <module>\\\\\\\\n    df = pd.read_csv(\\\\\\\\\\\\\\\"/home/saim/Desktop/abor\\\\\\\\\\\\\\\", sep='\\\\\\\\\\\\\\\\t')\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\\\\\\\\\", line 211, in wrapper\\\\\\\\n    return func(*args, **kwargs)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/util/_decorators.py\\\\\\\\\\\\\\\", line 317, in wrapper\\\\\\\\n    return func(*args, **kwargs)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 950, in read_csv\\\\\\\\n    return _read(filepath_or_buffer, kwds)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 605, in _read\\\\\\\\n    parser = TextFileReader(filepath_or_buffer, **kwds)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 1442, in __init__\\\\\\\\n    self._engine = self._make_engine(f, self.engine)\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/parsers/readers.py\\\\\\\\\\\\\\\", line 1729, in _make_engine\\\\\\\\n    self.handles = get_handle(\\\\\\\\n  File \\\\\\\\\\\\\\\"/azureml-envs/azureml_fdc05f88918fa818e3e93e934bd8223d/lib/python3.8/site-packages/pandas/io/common.py\\\\\\\\\\\\\\\", line 857, in get_handle\\\\\\\\n    handle = open(\\\\\\\\nFileNotFoundError: [Errno 2] No such file or directory: '/home/saim/Desktop/abor'\\\\\\\\n\\\\\\\\n'. Please check the log file 'user_logs/std_log.txt' for more details.\\\\\\\"}\\\\n{\\\\n  \\\\\\\"code\\\\\\\": \\\\\\\"ExecutionFailed\\\\\\\",\\\\n  \\\\\\\"target\\\\\\\": \\\\\\\"\\\\\\\",\\\\n  \\\\\\\"category\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n  \\\\\\\"error_details\\\\\\\": [\\\\n    {\\\\n      \\\\\\\"key\\\\\\\": \\\\\\\"exit_codes\\\\\\\",\\\\n      \\\\\\\"value\\\\\\\": \\\\\\\"1\\\\\\\"\\\\n    }\\\\n  ]\\\\n}\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\"\\n}\"\n    }\n}"
     ]
    }
   ],
   "source": [
    "from azureml.core import Experiment\n",
    "from azureml.pipeline.core import Pipeline\n",
    "from azureml.widgets import RunDetails\n",
    "\n",
    "# Construct the pipeline\n",
    "pipeline_steps = [prep_step, train_step]\n",
    "pipeline = Pipeline(workspace=ws, steps=pipeline_steps)\n",
    "print(\"Pipeline is built.\")\n",
    "\n",
    "# Create an experiment and run the pipeline\n",
    "experiment = Experiment(workspace=ws, name = 'mslearn-pipeline')\n",
    "pipeline_run = experiment.submit(pipeline, regenerate_outputs=True)\n",
    "print(\"Pipeline submitted for execution.\")\n",
    "RunDetails(pipeline_run).show()\n",
    "pipeline_run.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.12 ('azure_venv': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "c28328402f59a1b32b0411eb6249e1fa356fd21f2ee0c1ef48e94bb5004ad6f4"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
